### ISSUE TITLE
admin: integrate add product form  with picture upload script

### ISSUE THREAD

**Issue by mannycolon** [mannycolon/junkReSell#61]

**Comment by gvrojas** [comment]
I couldn't find a way to get the name of the file to also be passed into the addproductconfirm page. As a work around, I included a Confirm File option in the add product form so the name of the file could be sent to the addproductconfirm page. 

The way it would work is: the admin chooses a file, uploads the image, and  fills out the rest of the add product form. They are then required to confirm the file by choosing the file again. I hope this makes sense but I wan't sure how to do it another way. Let me know if you have any questions about it.

**Comment by mannycolon** [comment]
I will take a look and try find another way round do that.

**Comment by mannycolon** [comment]
#70
