### ISSUE TITLE
when adding a category we need to also add an image for the category so that it is display in the homepage

### ISSUE THREAD

**Issue by mannycolon** [mannycolon/junkReSell#62]

**Comment by mannycolon** [comment]
@gvrojas

**Comment by mannycolon** [comment]
<img width="418" alt="screen shot 2016-12-10 at 1 26 33 pm" src="https://cloud.githubusercontent.com/assets/17072300/21075304/4e7ff482-bedc-11e6-9b5e-1b2e5798022c.png">

**Comment by gvrojas** [comment]
Added file upload. Admin will need to upload image before submitting new category.
